services:
  endpoint:
    build:
      context: .
      dockerfile:
        Dockerfile
      args:
        PYTHON_VERSION: 3.12-slim
    command:
      ["uvicorn", "main:app", "--host",  "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - pg_shortener_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  pg_shortener_data:
